//
//  Uchen.swift
//  Markdown
//
//  Created by Leanne Northrop on 13/06/2015.
//  Copyright (c) 2015 Leanne Northrop. All rights reserved.
//
import Foundation
import UChen

public struct Uchen {
    public let WylieMap = [
        // Consonants
        "k" : "\u{0F40}",
        "kh" : "\u{0F41}",
        "g" : "\u{0F42}",
        "ng" : "\u{0F44}",
        "c" : "\u{0F45}",
        "ch" : "\u{0F46}",
        "j" : "\u{0F47}",
        "ny" : "\u{0F49}",
        "t" : "\u{0F4F}",
        "th" : "\u{0F50}",
        "d" : "\u{0F51}",
        "n" : "\u{0F53}",
        "p" : "\u{0F54}",
        "ph" : "\u{0F55}",
        "b" : "\u{0F56}",
        "m" : "\u{0F58}",
        "ts" : "\u{0F59}",
        "tsh" : "\u{0F5A}",
        "dz" : "\u{0F5B}",
        "w" : "\u{0F5D}",
        "zh" : "\u{0F5E}",
        "z" : "\u{0F5F}",
        "'" : "\u{0F60}",
        "y" : "\u{0F61}",
        "r" : "\u{0F62}",
        "l" : "\u{0F63}",
        "sh" : "\u{0F64}",
        "s" : "\u{0F66}",
        "h" : "\u{0F67}",
        "a" : "\u{0F68}",
        
        ".k" : "\u{0F40}",
        ".kh" : "\u{0F41}",
        ".g" : "\u{0F42}",
        ".ng" : "\u{0F44}",
        ".c" : "\u{0F45}",
        ".ch" : "\u{0F46}",
        ".j" : "\u{0F47}",
        ".ny" : "\u{0F49}",
        ".t" : "\u{0F4F}",
        ".th" : "\u{0F50}",
        ".d" : "\u{0F51}",
        ".n" : "\u{0F53}",
        ".p" : "\u{0F54}",
        ".ph" : "\u{0F55}",
        ".b" : "\u{0F56}",
        ".m" : "\u{0F58}",
        ".ts" : "\u{0F59}",
        ".tsh" : "\u{0F5A}",
        ".dz" : "\u{0F5B}",
        ".w" : "\u{0F5D}",
        ".zh" : "\u{0F5E}",
        ".z" : "\u{0F5F}",
        ".'" : "\u{0F60}",
        ".y" : "\u{0F61}",
        ".r" : "\u{0F62}",
        ".l" : "\u{0F63}",
        ".sh" : "\u{0F64}",
        ".s" : "\u{0F66}",
        ".h" : "\u{0F67}",
        ".a" : "\u{0F68}",
        
        "ka" : "\u{0F40}",
        "kha" : "\u{0F41}",
        "ga" : "\u{0F42}",
        "nga" : "\u{0F44}",
        "ca" : "\u{0F45}",
        "cha" : "\u{0F46}",
        "ja" : "\u{0F47}",
        "nya" : "\u{0F49}",
        "ta" : "\u{0F4F}",
        "tha" : "\u{0F50}",
        "da" : "\u{0F51}",
        "na" : "\u{0F53}",
        "pa" : "\u{0F54}",
        "pha" : "\u{0F55}",
        "ba" : "\u{0F56}",
        "ma" : "\u{0F58}",
        "tsa" : "\u{0F59}",
        "tsha" : "\u{0F5A}",
        "dza" : "\u{0F5B}",
        "wa" : "\u{0F5D}",
        "zha" : "\u{0F5E}",
        "za" : "\u{0F5F}",
        "ya" : "\u{0F61}",
        "ra" : "\u{0F62}",
        "la" : "\u{0F63}",
        "sha" : "\u{0F64}",
        "sa" : "\u{0F66}",
        "ha" : "\u{0F67}",
        
        ".ka" : "\u{0F40}",
        ".kha" : "\u{0F41}",
        ".ga" : "\u{0F42}",
        ".nga" : "\u{0F44}",
        ".ca" : "\u{0F45}",
        ".cha" : "\u{0F46}",
        ".ja" : "\u{0F47}",
        ".nya" : "\u{0F49}",
        ".ta" : "\u{0F4F}",
        ".tha" : "\u{0F50}",
        ".da" : "\u{0F51}",
        ".na" : "\u{0F53}",
        ".pa" : "\u{0F54}",
        ".pha" : "\u{0F55}",
        ".ba" : "\u{0F56}",
        ".ma" : "\u{0F58}",
        ".tsa" : "\u{0F59}",
        ".tsha" : "\u{0F5A}",
        ".dza" : "\u{0F5B}",
        ".wa" : "\u{0F5D}",
        ".zha" : "\u{0F5E}",
        ".za" : "\u{0F5F}",
        ".ya" : "\u{0F61}",
        ".ra" : "\u{0F62}",
        ".la" : "\u{0F63}",
        ".sha" : "\u{0F64}",
        ".sa" : "\u{0F66}",
        ".ha" : "\u{0F67}",
        
        // Sanskrit & Subjoined Sanskrit
        "gh" : "\u{0F43}",
        "g+h" : "\u{0F43}",
        "dh" : "\u{0F52}",
        "d+h" : "\u{0F52}",
        "bh" : "\u{0F57}",
        "b+h" : "\u{0F57}",
        "dzh" : "\u{0F5C}",
        "dz+h" : "\u{0F5C}",
        "kSh" : "\u{0F69}",
        "k+Sh" : "\u{0F69}",
        "T" : "\u{0F4A}",
        "Th" : "\u{0F4B}",
        "D" : "\u{0F4C}",
        "Dh" : "\u{0F4D}",
        "D+h" : "\u{0F4D}",
        "N" : "\u{0F4E}",
        "Sh" : "\u{0F65}",
        "oM" : "\u{0F00}",
        "+W" : "\u{0FBA}",
        "+Y" : "\u{0FBB}",
        "+R" : "\u{0FBC}",
        "H" : "\u{0F7F}",
        "M" : "\u{0F7E}",
        "~M" : "\u{0F83}",
        "~M'" : "\u{0F82}",
        "~?" : "\u{0F84}",
        "&" : "\u{0F85}",
        
        // Subjoined Consonants
        "+k" : "\u{0F90}",
        "+kh" : "\u{0F91}",
        "+g" : "\u{0F92}",
        "+gh" : "\u{0F93}",
        "+ng" : "\u{0F94}",
        "+c" : "\u{0F95}",
        "+ch" : "\u{0F96}",
        "+j" : "\u{0F97}",
        "+ny" : "\u{0F99}",
        "+th" : "\u{0FA0}",
        "+n" : "\u{0F9E}",
        "+t" : "\u{0F9F}",
        "+d" : "\u{0FA1}",
        "+dh" : "\u{0FA2}",
        //"+n" : "\u{0FA3}",
        "+p" : "\u{0FA4}",
        "+ph" : "\u{0FA5}",
        "+b" : "\u{0FA6}",
        "+bh" : "\u{0FA7}",
        "+m" : "\u{0FA8}",
        "+ts" : "\u{0FA9}",
        "+tsh" : "\u{0FAA}",
        "+dz" : "\u{0FAB}",
        "+dzh" : "\u{0FAC}",
        "+w" : "\u{0FAD}",
        "+zh" : "\u{0FAE}",
        "+z" : "\u{0FAF}",
        "+a" : "\u{0FB0}",
        "+'" : "\u{0FB0}",
        "+y" : "\u{0FB1}",
        "+r" : "\u{0FB2}",
        "+l" : "\u{0FB3}",
        "+sh" : "\u{0FB4}",
        "+s" : "\u{0FB6}",
        "+h" : "\u{0FB7}",
        "+A" : "\u{0FB8}",
        "+ksh" : "\u{0FB9}",
        "+.w" : "\u{0FBA}",
        "+.y" : "\u{0FBB}",
        "+.r" : "\u{0FBC}",
        
        "+ka" : "\u{0F90}",
        "+kha" : "\u{0F91}",
        "+ga" : "\u{0F92}",
        "+gha" : "\u{0F93}",
        "+nga" : "\u{0F94}",
        "+ca" : "\u{0F95}",
        "+cha" : "\u{0F96}",
        "+ja" : "\u{0F97}",
        "+nya" : "\u{0F99}",
        "+tha" : "\u{0FA0}",
        "+na" : "\u{0F9E}",
        "+ta" : "\u{0F9F}",
        "+da" : "\u{0FA1}",
        "+dha" : "\u{0FA2}",
        //"+na" : "\u{0FA3}",
        "+pa" : "\u{0FA4}",
        "+pha" : "\u{0FA5}",
        "+ba" : "\u{0FA6}",
        "+bha" : "\u{0FA7}",
        "+ma" : "\u{0FA8}",
        "+tsa" : "\u{0FA9}",
        "+tsha" : "\u{0FAA}",
        "+dza" : "\u{0FAB}",
        "+dzha" : "\u{0FAC}",
        "+wa" : "\u{0FAD}",
        "+zha" : "\u{0FAE}",
        "+za" : "\u{0FAF}",
        "+ya" : "\u{0FB1}",
        "+ra" : "\u{0FB2}",
        "+la" : "\u{0FB3}",
        "+sha" : "\u{0FB4}",
        "+sa" : "\u{0FB6}",
        "+ha" : "\u{0FB7}",
        "+.wa" : "\u{0FBA}",
        "+.ya" : "\u{0FBB}",
        "+.ra" : "\u{0FBC}",
        
        // Vowels
        "i" : "\u{0F72}",
        "u" : "\u{0F74}",
        "e" : "\u{0F7A}",
        "o" : "\u{0F7C}",
        "A" : "\u{0F71}",
        "I" : "\u{0F73}",
        "U" : "\u{0F75}",
        "r-i" : "\u{0F76}",
        "l-i" : "\u{0F78}",
        "-i" : "\u{0F80}",
        "ai" : "\u{0F7B}",
        "au" : "\u{0F7D}",
        "r-I" : "\u{0F77}",
        "l-I" : "\u{0F79}",
        "-I" : "\u{0F81}",
        
        // Numbers
        "0" : "\u{0F20}",
        "1" : "\u{0F21}",
        "2" : "\u{0F22}",
        "3" : "\u{0F23}",
        "4" : "\u{0F24}",
        "5" : "\u{0F25}",
        "6" : "\u{0F26}",
        "7" : "\u{0F27}",
        "8" : "\u{0F28}",
        "9" : "\u{0F29}",
        
        //Punctuation
        "_" : " }",
        " " : "\u{0F0B}",
        "*" : "\u{0F0C}",
        "/" : "\u{0F0D}",
        "//" : "\u{0F0E}",
        "," : "\u{0F0F}",
        "|" : "\u{0F11}",
        "!" : "\u{0F08}",
        ":" : "\u{0F14}",
        "£" : "\u{0F10}",
        "¬" : "\u{0F12}",
        "=" : "\u{0F34}",
        "x" : "\u{0FBE}",
        "x." : "\u{0FBF}",
        "...." : "\u{0F36}",
        "o...." : "\u{0F13}",
        "H1" : "\u{0F01}",
        "H2" : "\u{0F02}",
        "H3" : "\u{0F03}",
        "@" : "\u{0F04}",
        "#" : "\u{0F05}",
        "$" : "\u{0F06}",
        "%" : "\u{0F07}",
        "H4" : "\u{0F09}",
        "H5" : "\u{0F0A}",
        "H6" : "\u{0FD0}",
        "H7" : "\u{0FD1}",
        "<" : "\u{0F3A}",
        ">" : "\u{0F3B}",
        "(" : "\u{0F3C}",
        ")" : "\u{0F3D}",
    ]
    public let WylieLigatures = [
        // Ligatures & Special Character or Character Combinations
        "rk" : "r+k",
        "rg" : "r+g",
        "rng" : "r+ng",
        "rj" : "r+j",
        "rny" : "r+ny",
        "rt" : "r+t",
        "rd" : "r+d",
        "rn" : "r+n",
        "rb" : "r+b",
        "rm" : "r+m",
        "rts" : "r+ts",
        "rdz" : "r+dz",
        "lk" : "l+k",
        "lg" : "l+g",
        "lng" : "l+ng",
        "lc" : "l+c",
        "lj" : "l+j",
        "lt" : "l+t",
        "ld" : "l+d",
        "lp" : "l+p",
        "lb" : "l+b",
        "lh" : "l+h",
        "sk" : "s+k",
        "sg" : "s+g",
        "sng" : "s+ng",
        "sny" : "s+ny",
        "st" : "s+t",
        "sd" : "s+d",
        "sn" : "s+n",
        "sp" : "s+p",
        "sb" : "s+b",
        "sm" : "s+m",
        "sts" : "s+ts",
        "kw" : "k+w",
        "khw" : "kh+w",
        "gw" : "g+w",
        "cw" : "c+w",
        "nyw" : "ny+w",
        "tw" : "t+w",
        "dw" : "d+w",
        "tsw" : "ts+w",
        "tshw" : "tsh+w",
        "zhw" : "zh+w",
        "zw" : "z+w",
        "rw" : "r+w",
        "shw" : "sh+w",
        "sw" : "s+w",
        "hw" : "h+w",
        "ky" : "k+y",
        "khy" : "kh+y",
        "gy" : "g+y",
        "py" : "p+y",
        "phy" : "ph+y",
        "by" : "b+y",
        "my" : "m+y",
        "kr" : "k+r",
        "khr" : "kh+r",
        "gr" : "g+r",
        "tr" : "t+r",
        "thr" : "th+r",
        "dr" : "d+r",
        "pr" : "p+r",
        "phr" : "ph+r",
        "br" : "b+r",
        "mr" : "m+r",
        "shr" : "sh+r",
        "sr" : "s+r",
        "hr" : "h+r",
        "kl" : "k+l",
        "gl" : "g+l",
        "bl" : "b+l",
        "zl" : "z+l",
        "rl" : "r+l",
        "sl" : "s+l",
        "rky" : "r+k+y",
        "rgy" : "r+g+y",
        "rmy" : "r+m+y",
        "rgw" : "r+g+w",
        "rtsw" : "r+ts+w",
        "sky" : "s+k+y",
        "sgy" : "s+g+y",
        "spy" : "s+p+y",
        "sby" : "s+b+y",
        "smy" : "s+m+y",
        "skr" : "s+k+r",
        "sgr" : "s+g+r",
        "snr" : "s+n+r",
        "spr" : "s+p+r",
        "sbr" : "s+b+r",
        "smr" : "s+m+r",
        "grw" : "g+r+w",
        "drw" : "d+r+w",
        "phyw" : "ph+y+w",
        "~om" : "\u{0F00}",
        "~athung" : "\u{0F01}",
        "~namcheyma" : "\u{0F02}",
        "~tertsekma" : "\u{0F03}",
        "~dunma" : "\u{0F04}",
        "~kabma" : "\u{0F05}",
        "~pursheyma" : "\u{0F06}",
        "~tseksheyma" : "\u{0F07}",
        "~drulshey" : "\u{0F08}",
        "~kuryikgo" : "\u{0F09}",
        "~kashoyikgo" : "\u{0F0A}",
        "~tsek" : "\u{0F0B}",
        "~tsektar" : "\u{0F0C}",
        "~shey" : "\u{0F0D}",
        "~nyishey" : "\u{0F0E}",
        "~tsekshey" : "\u{0F0F}",
        "~nyitsekshey" : "\u{0F10}",
        "~rinchenpungshey" : "\u{0F11}",
        "~gyatramshey" : "\u{0F12}",
        "~dzutamelongchen" : "\u{0F13}",
        "~tertsek" : "\u{0F14}",
        "~cheta" : "\u{0F15}",
        "~lakta" : "\u{0F16}",
        "~trachencharta" : "\u{0F17}",
        "~kyupa" : "\u{0F18}",
        "~dongtsu" : "\u{0F19}",
        "~dekachig" : "\u{0F1A}",
        "~dekanyi" : "\u{0F1B}",
        "~dekasum" : "\u{0F1C}",
        "~denachig" : "\u{0F1D}",
        "~denanyi" : "\u{0F1E}",
        "~dekadena" : "\u{0F1F}",
        "~duta" : "\u{0F34}",
        "~ngezungnyida" : "\u{0F35}",
        "~dzutashimigchen" : "\u{0F36}",
        "~ngezunggorta" : "\u{0F37}",
        "~chego" : "\u{0F38}",
        "~tsatru" : "\u{0F39}",
        "~gugtayun" : "\u{0F3A}",
        "~gugtaye" : "\u{0F3B}",
        "~angkangyun" : "\u{0F3C}",
        "~angkangye" : "\u{0F3D}",
        "~yartse" : "\u{0F3E}",
        "~martse" : "\u{0F3F}",
        "~kuruka" : "\u{0FBE}",
        "~kurukashimikchen" : "\u{0FBF}",
        "~HEAVY" : "\u{0FC0}",
        "~LIGHT" : "\u{0FC1}",
        "~CANGTE" : "\u{0FC2}",
        "~SBUB" : "\u{0FC3}",
        "~drilbu" : "\u{0FC4}",
        "~dorje" : "\u{0FC5}",
        "~pemaden" : "\u{0FC6}",
        "~dorjegyadram" : "\u{0FC7}",
        "~phurba" : "\u{0FC8}",
        "~norbu" : "\u{0FC9}",
        "~norbunyikhyi" : "\u{0FCA}",
        "~norbusumkhyi" : "\u{0FCB}",
        "~norbushikhyi" : "\u{0FCC}",
        "~denasum" : "\u{0FCF}",
    ]
    
    var _sortedLigatureKeys = [String]()
    var _sortedKeys = [String]()
    
    public init() {
        var keys = self.WylieLigatures.keys.array
        keys.sort { count($0) > count($1) }
        _sortedLigatureKeys = keys
        keys = self.WylieMap.keys.array
        keys.sort { count($0) > count($1) }
        _sortedKeys = keys
    }
    
    public func translate(text:String) -> String {
        func apply(str : String, substitutions : [String], map : [String:String]) -> String {
            var result = str;
            for (var i = 0; i < substitutions.count; i++) {
                let key = substitutions[i]
                let match = result.rangeOfString(key, options: .LiteralSearch)
                if match != nil {
                    result = result.stringByReplacingOccurrencesOfString(key,
                                                                        withString: map[key]!,
                                                                        options: NSStringCompareOptions.LiteralSearch,
                                                                        range: nil)
                }
            }
            return result;
        }
        
        func parseSyllable (syllable : String) -> String {
            var result = "";
            result = apply(apply(syllable, _sortedLigatureKeys, WylieLigatures), _sortedKeys, WylieMap);
            return result;
        }

        var result = "";
        
        var syllables : [String] = text.componentsSeparatedByString(" ");
        var tsheg : String = self.WylieMap[" "]!
        for (var i : Int = 0; i < syllables.count; i++) {
            if i == syllables.count - 1 { tsheg = "" }
            result += parseSyllable(syllables[i]) + tsheg;
        }
        
        return result;

    }
    
}
